language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.3.7
  - DJANGO=django==1.4.12
  - DJANGO=django==1.4.12 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==1.5.7
  - DJANGO=django==1.5.7 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==1.6.4
  - DJANGO=https://github.com/django/django/tarball/stable/1.7.x
  - DJANGO=django==1.6.4 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=https://github.com/django/django/tarball/stable/1.7.x DATABASE_URL=postgres://postgres@localhost/test

install:
  - pip install -q $DJANGO && pip install sphinx argparse psycopg2
  - python setup.py -q install
before_script:
  - psql -c 'create database test;' -U postgres
script: python runtests.py
matrix:
  exclude:
    - python: 3.4
      env: DJANGO=django==1.6.4
    - python: 3.4
      env: DJANGO=django==1.6.4 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.4
      env: DJANGO=django==1.5.7
    - python: 3.4
      env: DJANGO=django==1.5.7 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.4
      env: DJANGO=django==1.4.12
    - python: 3.4
      env: DJANGO=django==1.4.12 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.4
      env: DJANGO=django==1.3.7
    - python: 3.3
      env: DJANGO=django==1.4.12
    - python: 3.3
      env: DJANGO=django==1.4.12 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.3
      env: DJANGO=django==1.3.7
    - python: 2.6
      env: DJANGO=https://github.com/django/django/tarball/stable/1.7.x
    - python: 2.6
      env: DJANGO=https://github.com/django/django/tarball/stable/1.7.x DATABASE_URL=postgres://postgres@localhost/test
    - python: 2.6
      env: DJANGO=django==1.6.4
    - python: 2.6
      env: DJANGO=django==1.6.4 DATABASE_URL=postgres://postgres@localhost/test
